# prometheus.yml
global:
  scrape_interval: 5s
  
  external_labels:
    monitor: 'my-monitor'


scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          group: 'local'
         
  - job_name: 'mongodb_exporter'
    static_configs:
      - targets: ['mongodb_exporter:9001']
        labels:
          group: db1